[profile.default]
solc_version = "0.8.25"
forge_version = "1.4.4"
src = 'contracts/v2'
test = 'test/v2'
libs = ['lib', 'node_modules']
remappings = ['@openzeppelin/contracts=node_modules/@openzeppelin/contracts']
via_ir = true
optimizer = true
optimizer_runs = 200
gas_reports = ['FeePool', 'JobRouter']

[profile.gas]
src = 'contracts/gas'
test = 'test/gas'
libs = ['lib', 'node_modules']
remappings = ['@openzeppelin/contracts=node_modules/@openzeppelin/contracts']
via_ir = true
optimizer = true
optimizer_runs = 200
forge_version = "1.4.4"
